# Generated by Django 3.2.6 on 2021-09-03 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eff', '0002_delete_infoactivos'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoActivosModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_mercado', models.TextField()),
                ('rentabilidades', models.JSONField()),
                ('volatilidades', models.JSONField()),
            ],
        ),
    ]
