# Generated by Django 3.2.6 on 2021-09-03 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eff', '0003_infoactivosmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='infoactivosmodel',
            name='num_activos',
            field=models.IntegerField(default=3),
        ),
    ]
